version: 2
jobs:
  xcode9: &xcode-job
    macos:
      xcode: "9.4.1"
    steps:
      - run:
          name: Install C++ dependencies
          command: brew install fmt cmake apache-arrow boost rapidjson howard-hinnant-date pybind11
      - run:
          name: Install Python dependencies
          command: pip3 install numpy seaborn sklearn
      - checkout
      - run:
          name: Configure Dataframes CMake
          command: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ../native_libs/src
      - run:
          name: Build Dataframes C++ parts on macos
          command: |
            cd build
            make -j 2
  xcode10:
    <<: *xcode-job
    macos:
      xcode: "10.0.0"



workflows:
  version: 2
  build_and_test:
    jobs:
      - xcode9
      - xcode10