name: dataframes-package
synopsis: Utility program to build, test and create relocatable package with Dataframes library
version: "1.0"
author: New Byte Order <contact@newbyteorder.com>
maintainer: New Byte Order <contact@newbyteorder.com>

ghc-options: 
    -threaded 
    -Werror=missing-fields

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DoAndIfThenElse
- DuplicateRecordFields
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- LiberalTypeSynonyms
- MonadComprehensions
- MultiWayIf
- NamedWildCards
- NegativeLiterals
- NoImplicitPrelude
- NumDecimals
- OverloadedLabels
- OverloadedStrings
- PackageImports
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecursiveDo
- RecordWildCards
- RelaxedPolyRec
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- StrictData
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UnicodeSyntax
- ViewPatterns

library:
  source-dirs: src
tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies: dataframes-package
executable:
  main: Main.hs
  dependencies: dataframes-package

dependencies:
- async
- attoparsec
- base
- bytestring
- Cabal
- conduit
- conduit-extra
- containers
- directory
- errors
- extra
- file-embed
- filepath
- Glob
- http-conduit
- http-types
- lens
- MissingH
- neat-interpolation
- pecoff-fork
- process
- prologue
- safe-exceptions
- streaming-commons
# - streaming-process
- typed-process
- temporary
- text
- unix-compat
- unliftio-core
- utf8-string
